default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: storage/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

production:
  <<: *default
  # Renderは DATABASE_URL 環境変数を自動で読み込むため、
  # ここには最低限のadapter設定だけでOKです
  adapter: postgresql
  encoding: unicode